[package]
name = "substrate-minimal-runtime"
version = "0.1.0"
description = "Minimal Substrate runtime for testing compatibility"
publish = false

[workspace]

[package.metadata.release]
release = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-support = { git = "https://github.com/paritytech/polkadot-sdk/", branch = "release-polkadot-v1.1.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk/", branch = "release-polkadot-v1.1.0", default-features = false, features = [
  "serde",
] }
jwt-compact = { path = "../..", default-features = false, features = ["ed25519-compact"]}

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/polkadot-sdk/", branch = "release-polkadot-v1.4.0", optional = true }

[features]
default = ["std"]
std = ["frame-support/std", "substrate-wasm-builder", "jwt-compact/std"]
